### PR TITLE
v2.5.0

### PR DESCRIPTION
**Pull request by bugsounet**
Vulnerabilities: deleted :)
Update dependencies:
 * @types/node
 * @mapbox/node-pre-gyp

Add:
 * eslint

Fix: 
 * code with eslint (flat config)

### CODE REVIEW

**Comment by bugsounet** [comment]
EXT-Detector by bugsounet : 
 * Issues are not enabled in the GitHub repository. So users cannot report bugs. Please enable issues in your repo. 

@KristjanESPERANTO: All is ok for me for testing your new rules

**Comment by bugsounet** [comment]
I keep open for any modifications :)

**Comment by KristjanESPERANTO** [comment]
Nice. With that changes my scripts don't find anything to complain about :clap: 

What do you think about another image? That Google G doesn't say much. Maybe a ear like this: https://openclipart.org/detail/269019/ear?

**Comment by bugsounet** [comment]
sure but I use `G` in main module displayer (Google icon for MMM-GoogleAssistant)

I don't know how you choose Image for your app

**Comment by KristjanESPERANTO** [comment]
> I don't know how you choose Image for your app

_The script also adds an image. To do this, it searches the module's repo for an image that begins with "screenshot" or "example". If it doesn't find anything like that, it takes the first image it finds in the repo._

So in this module it chooses [google.png](https://github.com/bugsounet/EXT-Detector/blob/main/resources/google.png). If you would add an image e.g. with the name `ear_listening-smybolization.png` to the same directory, it would choose this because e is before g.

**Pull request merged**
